# UZHFPV Config

# Initial standard deviations (attitude, velocity, position)
extended_pose_std: [1.0e-1, 1.0e-1, 1.0e-9, 1.0e-1, 1.0e-1, 1.0e-1, 1.0e-9, 1.0e-9, 1.0e-9]
bias_std: [1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1]
extrinsics_std: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
intrinsics_std: [1.0, 1.0, 1.0, 1.0]

# IMU noise statistics
accelerometer_noise_density: 0.1
accelerometer_random_walk: 0.002
gyroscope_noise_density: 0.05
gyroscope_random_walk: 4.0e-05 

# Camera calibration
distortion_coeffs: [-0.013721808247486035, 0.020727425669427896, -0.012786476702685545, 0.0025242267320687625]
distortion_model: equidistant
resolution: [640, 480]
intrinsics: [278.66723066149086, 278.48991409740296, 319.75221200593535, 241.96858910358173]
T_cam_imu:
  - [-0.028228787368606456, -0.999601488301944, 1.2175294828553618e-05, 0.02172388268966517]
  - [0.014401251861751119, -0.00041887083271471837, -0.9998962088597202, -6.605455433829172e-05]
  - [0.999497743623523, -0.028225682131089447, 0.014407337010089172, -0.00048817563004522853]
  - [0.0, 0.0, 0.0, 1.0]

# Initializer
static_initializer_imu_window: 2.0
static_initializer_acc_threshold: 0.4

# Checker
checker_disparity_window: 0.5
checker_disparity_threshold: 4.0

# Propagator
state_transition_order: -1
imu_buffer_max_size: 1000

# Updater
refine_traingulation: true
feature_min_depth: 0.1
feature_max_depth: 30
feature_refinement_max_iterations: 20
feature_refinement_tollerance: 1e-10
measurement_projection_method: unit_plane
feature_representation: anchored_inverse_depth
pixel_standerd_deviation: 1.5
curvature_correction: true
min_angle_deg: 1.0
zero_velocity_update: enabled

# State options
enable_camera_intrinsic_calibration: false
gravity: 9.8065
num_clones: 11

# Tracker
equalization_method: histogram
optical_flow_pyramid_levels: 3
detector_pyramid_levels: 1
feature_detector: fast
grid_x_size: 3
grid_y_size: 3
min_feature_pixel_distance: 10
min_features: 140
max_features: 160
fast_threshold: 50
shi_tomasi_quality_level: 0.75

# Track Manager
max_track_length: 150

# Logger level [0: Full, 1: INFO, 2: WARN, 3: ERR, 4: INACTIVE]
logger_level: 1